### ISSUE TITLE
Support record creation

### ISSUE THREAD

**Issue by joefitzgerald** [adlio/harvest#2]
It would be ideal if the API had function(s) that facilitated the creation of records via the Harvest API (for example, projects). The API currently has a `Get` function, and this would imply the addition of a `Post` function along with resource-specific functions that make use of the `Post` function for their resource.

What are your thoughts on this?

**Comment by adlio** [comment]
Totally agreed. The long term plan is to support all operations. My uses to-date have been read only. Willing to accept pull requests, and I do plan to eventually work on these kinds of additions.
